// File: resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**

        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/customers/**

management:
  endpoints:
    web:
      exposure:
        include: "*"