server:
  port: 8082
spring:
  application:
    name: inventory-service

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

  retry:
    instances:
      paymentService:
        maxAttempts: 3
        waitDuration: 2s

  ratelimiter:
    instances:
      paymentService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s

  timelimiter:
    instances:
      paymentService:
        timeoutDuration: 3s

  logging:
    level:
      io.github.resilience4j: DEBUG
